[package]
name = "rush"
version = "0.1.0"
authors = ["jordan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "6.2.0"
nix = "0.17.0"